/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue.Parametres;

import Util.DateModulable;
import Vue.Menu2;
import java.awt.Container;
import java.awt.FlowLayout;

/**
 * Classe de la fenetre des parametres
 * @author Yanek
 */
public class ParametreJFrame extends javax.swing.JFrame {

    Menu2 caller;
    
    /**
     * Creates new form NewJFrame
     * @param caller La frame appelante
     */
    public ParametreJFrame(Menu2 caller) {
        this.caller = caller;
        initComponents();
        this.setLocationRelativeTo(null); // positionner la fenetre au centre de l'écran
        Container content = this.getContentPane();
        content.setLayout(new FlowLayout(FlowLayout.CENTER));
        this.setResizable(false); //la fenetre ne peut pas etre redimensionée
        this.pack();
        jTextFieldDate.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelModifDate = new javax.swing.JPanel();
        jTextFieldDate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonJour = new javax.swing.JButton();
        jButtonMois = new javax.swing.JButton();
        jButtonAn = new javax.swing.JButton();
        jButtonAnMoins = new javax.swing.JButton();
        jButtonMoisMoins = new javax.swing.JButton();
        jButtonJourMoins = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldDate.setText(DateModulable.getDateString());

        jLabel1.setText("Date actuelle : ");

        jButtonJour.setText("+1 jour");
        jButtonJour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJourActionPerformed(evt);
            }
        });

        jButtonMois.setText("+1 mois");
        jButtonMois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoisActionPerformed(evt);
            }
        });

        jButtonAn.setText("+1 an");
        jButtonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnActionPerformed(evt);
            }
        });

        jButtonAnMoins.setText("-1 an");
        jButtonAnMoins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnMoinsActionPerformed(evt);
            }
        });

        jButtonMoisMoins.setText("-1 mois");
        jButtonMoisMoins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoisMoinsActionPerformed(evt);
            }
        });

        jButtonJourMoins.setText("-1 jour");
        jButtonJourMoins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJourMoinsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelModifDateLayout = new javax.swing.GroupLayout(jPanelModifDate);
        jPanelModifDate.setLayout(jPanelModifDateLayout);
        jPanelModifDateLayout.setHorizontalGroup(
            jPanelModifDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModifDateLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanelModifDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jButtonJour)
                    .addComponent(jButtonJourMoins))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelModifDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelModifDateLayout.createSequentialGroup()
                        .addGroup(jPanelModifDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonMoisMoins)
                            .addComponent(jButtonMois))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelModifDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonAn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAnMoins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanelModifDateLayout.setVerticalGroup(
            jPanelModifDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModifDateLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanelModifDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelModifDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonJour)
                    .addComponent(jButtonMois)
                    .addComponent(jButtonAn))
                .addGap(18, 18, 18)
                .addGroup(jPanelModifDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonJourMoins)
                    .addComponent(jButtonMoisMoins)
                    .addComponent(jButtonAnMoins))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelModifDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelModifDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJourActionPerformed
        DateModulable.inc(1,0,0);
        jTextFieldDate.setText(DateModulable.getDateString());
        caller.updateDate();
    }//GEN-LAST:event_jButtonJourActionPerformed

    private void jButtonMoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoisActionPerformed
        DateModulable.inc(0,1,0);
        jTextFieldDate.setText(DateModulable.getDateString());
        caller.updateDate();
    }//GEN-LAST:event_jButtonMoisActionPerformed

    private void jButtonAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnActionPerformed
        DateModulable.inc(0,0,1);
        jTextFieldDate.setText(DateModulable.getDateString());
        caller.updateDate();
    }//GEN-LAST:event_jButtonAnActionPerformed

    private void jButtonAnMoinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnMoinsActionPerformed
        DateModulable.inc(0,0,-1);
        jTextFieldDate.setText(DateModulable.getDateString());
        caller.updateDate();
    }//GEN-LAST:event_jButtonAnMoinsActionPerformed

    private void jButtonMoisMoinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoisMoinsActionPerformed
        DateModulable.inc(0,-1,0);
        jTextFieldDate.setText(DateModulable.getDateString());
        caller.updateDate();
    }//GEN-LAST:event_jButtonMoisMoinsActionPerformed

    private void jButtonJourMoinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJourMoinsActionPerformed
        DateModulable.inc(-1,0,0);
        jTextFieldDate.setText(DateModulable.getDateString());
        caller.updateDate();
    }//GEN-LAST:event_jButtonJourMoinsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAn;
    private javax.swing.JButton jButtonAnMoins;
    private javax.swing.JButton jButtonJour;
    private javax.swing.JButton jButtonJourMoins;
    private javax.swing.JButton jButtonMois;
    private javax.swing.JButton jButtonMoisMoins;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelModifDate;
    private javax.swing.JTextField jTextFieldDate;
    // End of variables declaration//GEN-END:variables
}
